#!/usr/bin/env node

/**
 * Generate version information including git commit hash
 * This script is run during the build process
 */

import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function getGitCommitHash() {
  try {
    const hash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
    return hash;
  } catch (error) {
    console.warn('Warning: Could not get git commit hash:', error.message);
    return 'unknown';
  }
}

function getGitBranch() {
  try {
    const branch = execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf-8' }).trim();
    return branch;
  } catch (error) {
    console.warn('Warning: Could not get git branch:', error.message);
    return 'unknown';
  }
}

function getGitCommitDate() {
  try {
    const date = execSync('git log -1 --format=%cd --date=short', { encoding: 'utf-8' }).trim();
    return date;
  } catch (error) {
    console.warn('Warning: Could not get git commit date:', error.message);
    return 'unknown';
  }
}

const version = {
  version: '0.2',
  commit: getGitCommitHash(),
  branch: getGitBranch(),
  commitDate: getGitCommitDate(),
  buildDate: new Date().toISOString().split('T')[0]
};

const outputPath = join(__dirname, '../src/lib/version.js');
const content = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION_INFO = ${JSON.stringify(version, null, 2)};
`;

writeFileSync(outputPath, content, 'utf-8');
console.log('Version info generated:', version);
console.log('Written to:', outputPath);
